### ISSUE TITLE
Multiple output redirection to the same file

### ISSUE THREAD

**Issue by rotanov** [klenin/Spawner#18]
Consider the following `sp.exe --separator=// --// --out=output.txt 1.exe --// --out=output.txt 2.exe`

Now only `1.exe` will gain write access to the `output.txt`. Setting share mode to `FILE_SHARE_READ | FILE_SHARE_WRITE` doesn't solve the problem.

Consider open file handle, write, close file handle for each write.

**Comment by klenin** [comment]
Fixed in the last rewrite.
