### ISSUE TITLE
Access Violation when trying to dereference pointer to unexisting (or unavailable for process) memory mistreated as Security Violation

### ISSUE THREAD

**Issue by brigaccess** [klenin/Spawner#40]
Admin-only: https://imcs.dvfu.ru/cats/main.pl?rid=1084417;cid=1051013;f=run_details

Although the code itself is harmless, dereferencing of invalid pointer leads to Access Violation, which is treated as a hacking attempt. I think, that "Runtime Exception" describes this situation more obviously.

**Comment by klenin** [comment]
No, AV happened on test 8, which is indeed marked as RE.
Test 2 caused "write limit exceeded", which is currently treated as SV (see klenin/cats-main#116).
